export const metadata = {
  title: "Shopping Area",
  description: "Generated by create next app",
};
export default function Layout({ children }){
  return (
    <div>
      {children}
    </div>
  );
}
